edition: 1.0.0 #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: photoview #  项目名称
access: "default" #  秘钥别名

vars: # 全局变量
  region: {{ region }}
  service:
    name: {{ serviceName }}
    description: '云相册'
    internetAccess: true
services:
  photoview:
    component: fc
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: {{functionName}}
        description:
        # codeUri: ./photo_view_latest
        memorySize: 3072
        runtime: custom-container
        timeout: 60
        caPort: 80
        customContainerConfig:
          image: registry.{{region}}.aliyuncs.com/serverless_dataapi/fc:0.1 #镜像由https://github.com/chengzhengyubian/fc-photoview-code代码构建
          command: '["/app/photoview"]'
        environmentVariables:
          ACCESS_KEY_ID: {{accessKeyId}}
          ACCESS_KEY_SECRET: {{accessKeySecret}}
          ENDPOINT: {{endpoint}}
          DATABASE: {{database}}
          RESOURCE_ARN: {{resourceArn}}
          SECRET_ARN: {{secretArn}}
          PHOTOVIEW_DEVELOPMENT_MODE: 1
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
                - POST
                - DELETE
                - PUT
                - OPTIONS